#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Chruby
source /usr/local/share/chruby/chruby.sh
chruby ruby-2.2

DEV_ROOT=~/development/backend_team/src
export DEV_ROOT
DEPENDENCY_DIRECTORY=$DEV_ROOT/dependencies
export DEPENDENCY_DIRECTORY

DEPENDENCY_MODULE_PATH=$DEV_ROOT/sifi_cmake
export DEPENDENCY_MODULE_PATH

alias dmake="cmake -DCMAKE_MODULE_PATH=$DEPENDENCY_MODULE_PATH -DDEPENDENCY_DIRECTORY=$DEPENDENCY_DIRECTORY -DCMAKE_BUILD_TYPE=Debug"
alias pmake="cmake -DCMAKE_MODULE_PATH=$DEPENDENCY_MODULE_PATH -DDEPENDENCY_DIRECTORY=$DEPENDENCY_DIRECTORY -DPRE_BUILT_DEPS=ON -DCMAKE_BUILD_TYPE=Debug"

DATA_BAG_PATH=$DEV_ROOT/chef-repo/data_bags
export DATA_BAG_PATH


# Customize to your needs...
